### ISSUE TITLE
panic: syscall: string with NUL passed to StringToUTF16

### ISSUE THREAD

**Issue by benmoss** [GoogleCloudPlatform/guest-agent#31]
Trying to run a powershell startup script on my machine and getting this error from the agent as its running:

```
panic: syscall: string with NUL passed to StringToUTF16

goroutine 1 [running]:
syscall.StringToUTF16(...)
        /tmp/go/src/syscall/syscall_windows.go:30
syscall.StringToUTF16Ptr(0xc0003657c0, 0x9a, 0x50)
        /tmp/go/src/syscall/syscall_windows.go:65 +0x8b
golang.org/x/sys/windows/svc/eventlog.(*Log).report(0xc00001e0f0, 0x37200000004, 0xc0003657c0, 0x9a, 0x1, 0xc0003fefa0)
        /usr/share/gocode/pkg/mod/golang.org/x/sys@v0.0.0-20200107162124-548cf772de50/windows/svc/eventlog/log.go:50 +0x40
golang.org/x/sys/windows/svc/eventlog.(*Log).Info(...)
        /usr/share/gocode/pkg/mod/golang.org/x/sys@v0.0.0-20200107162124-548cf772de50/windows/svc/eventlog/log.go:57
github.com/GoogleCloudPlatform/guest-logging-go/logger.local(0xc000411c00, 0x72, 0x0, 0x3, 0x1, 0xc0003fefa0, 0xc00041b640, 0x19)
        /usr/share/gocode/pkg/mod/github.com/!google!cloud!platform/guest-logging-go@v0.0.0-20191226203445-d798144cee48/logger/logger_windows.go:53 +0x11e
github.com/GoogleCloudPlatform/guest-logging-go/logger.Log(0xc000411c00, 0x72, 0x0, 0x3, 0x1, 0xc0003fefa0, 0xc00041b640, 0x19)
        /usr/share/gocode/pkg/mod/github.com/!google!cloud!platform/guest-logging-go@v0.0.0-20191226203445-d798144cee48/logger/logger.go:112 +0xdc
main.runCmd(0xc0002c91e0, 0xc00005d260, 0x1a, 0x0, 0x0)
        /guest-agent/google_metadata_script_runner/main.go:321 +0x2a6
main.runScript(0xb85640, 0xc00005e078, 0xc00005d260, 0x1a, 0xc0003382c0, 0x14e, 0x0, 0x0)
        /guest-agent/google_metadata_script_runner/main.go:301 +0x6ff
main.main()
        /guest-agent/google_metadata_script_runner/main.go:473 +0x516
```

**Comment by benmoss** [comment]
The relevant part of the startup script:

```
curl.exe -LO https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1
.\PrepareNode.ps1 -KubernetesVersion v1.17.0
```

**Comment by ChaitanyaKulkarni28** [comment]
Closing it as its pretty old and we had quite a few new releases. Please re-open or file another issue if you still notice this behavior.
